portfolio/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
from django.conf.urls import url
from django.urls import path, include
from projects.views import AboutView
from projects.views import contact

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('projects.urls', namespace='projects')),
    path('contact/', contact, name='contact'),
    path('about/', AboutView.as_view(), name='about'),
    url(r'download/(?P<path>.*)$', serve, {'download_root':settings.MEDIA_ROOT})
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projects/urls.py
from django.urls import path
from .views import AboutView, ProjectDetailView, ProjectHomeView, CategoryView

app_name = 'projects'

urlpatterns = [
    path('', ProjectHomeView.as_view(), name='project-home'),
    path('project<int:pk>/', ProjectDetailView.as_view(), name='project-detail'),
    path('category/<str:category_name>/', CategoryView, name='category-page'),
]

projects/models.py
from django.urls import reverse
from django.db import models
from django.db.models.fields import NullBooleanField
from django.db.models.signals import pre_delete
from django.dispatch.dispatcher import receiver
from django.contrib.auth.models import AbstractUser
from colorfield.fields import ColorField

class UserProfile(AbstractUser):
    pass

class Categorie(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return str(self.name)

class Project(models.Model):
    title = models.CharField(max_length=250)
    description = models.TextField(null=True, blank=True)
    category = models.CharField(max_length=255, default='Figma', null=True, blank=True)
    post_date = models.DateField(auto_now_add=True)
    post_time = models.TimeField(auto_now_add=True)
    image = models.CharField(max_length=250, null=True, blank=True)
    file = models.CharField(max_length=250, null=True, blank=True)
    case_study_file = models.CharField(max_length=250, null=True, blank=True)
    color_palette = models.BooleanField(default=False)
    color = ColorField(null=True, blank=True)
    color1 = ColorField(null=True, blank=True)
    color2 = ColorField(null=True, blank=True)
    color3 = ColorField(null=True, blank=True)

    def __str__(self):
        return str(self.title)
    
    def get_absolute_url(self):
        return reverse('project:project-home')

@receiver(pre_delete, sender=Project)
def Project_delete(sender, instance, **kwargs):
    instance.image.delete(False)

@receiver(pre_delete, sender=Project)
def Project_delete(sender, instance, **kwargs):
    instance.file.delete(False)

@receiver(pre_delete, sender=Project)
def Project_delete(sender, instance, **kwargs):
    instance.case_study_file.delete(False)

projects/views.py
from django.views.generic import ListView, DetailView, TemplateView
from django.shortcuts import render
from .models import Project, Categorie
from django.core.mail import send_mail

class ProjectHomeView(ListView):
    template_name = 'projects/index.html'
    queryset = Project.objects.all()
    context_object_name = 'projects'
    ordering = ['-post_date','-post_time']

    def get_context_data(self, *args, **kwargs):
        category_menu = Categorie.objects.all()
        context = super(ProjectHomeView, self).get_context_data(*args, **kwargs)
        context['category_menu'] = category_menu
        return context


class ProjectDetailView(DetailView):
    model = Project
    template_name = 'projects/project-detail.html'
    context_object_name = 'project'

class AboutView(TemplateView):
    template_name = 'projects/about.html'

def contact(request):
    if request.method == "POST":
        name = request.POST['name']
        email = request.POST['email']
        subject = request.POST['subject']
        message = request.POST['message']

        #send an email
        send_mail(
            subject,
            'Name : '+ name + ' | ' +'Email : ' + email + ' | ' +'Message : ' + message,
            email,
            ['joise1124@gmail.com']
        )
        return render(request, 'projects/contact.html', {'name':name})
    else:
        return render(request, 'projects/contact.html', {})

def CategoryView(request, category_name):
    category_projects = Project.objects.filter(category=category_name)
    return render(request, 'projects/category.html', {'category_name':category_name, 'category_projects':category_projects})

projects/templates/projects/about.html
{% extends 'base.html' %}
{% load static %}
{% block title %}About{% endblock title %}
{% block content %}
<div class="group">
    <div class="card">
        <div class="row">
            <div class="col-md-6 col-12">
                <img class="img-fluid profile-pic" src="{% static 'images/profile.jpeg' %}" alt="">
            </div>
            <div class="col-md-6 col-12 text-container">
                <div class="heading">
                    <h3>About</h3>
                    <div class="line"></div>
                </div>
                <p>My name is Joise, I am a Web and UI Designer based in Kerala, India</p>
                <p>I planned on creating a design every week day until I reach 100 days total, to practice and improve my skills.</p>
                <p>I created this website to be able to share these designs as well as some web template with anybody who is interested in using them as inspiration or research material. I am hoping this project also takes me out of my comfort zone and provides new challenges. I'm planning to get better at development as well, so lots of exciting things to look out for!</p>
                <p>If you're interested in my journey stay tuned, and if you'd like to get in touch feel free to drop me a <a class="link" href="{% url 'contact' %}">message</a>.</p>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

projects/templates/projects/category.html
{% extends 'base.html' %}
{% block title %}{{category_name}} Projects{% endblock title %}
{% block content %}
{% load static %}
<div class="group">
    <div class="card banner shadow">
        <h3>Category</h3>
        <small class="text-muted">{{category_name}} Projects</small>
    </div>
    <div class="mt-5">
        <div class="row">
            {% for project in category_projects %}
            <div class="col-md-4 col-xxl-3 p-2 con">
                <a href="{% url 'projects:project-detail' project.pk %}" data-bs-toggle="tooltip" data-bs-placement="top" title="Click to know more">
                    <div class="card project-card" id="card">
                        <img src="{{project.image.url}}" class="card-img-top" alt="...">
                        <div class="card-body">
                            <a href="#" data-bs-toggle="tooltip" data-bs-placement="top" title="Filter Category"><div class="software-item
                            {% if project.category == 'Figma' %}figma{% endif %}
                            {% if project.category == 'Sketch' %}sketch{% endif %}
                            {% if project.category == 'XD' %}xd{% endif %}
                            {% if project.category == 'Bootstrap' %}bootstrap{% endif %}">
                            </div></a>
                            <h5 class="card-title">{{project.title}}</h5>
                        </div>
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
    
{% endblock content %}

projects/templates/projects/contact.html
{% extends 'base.html' %}
{% block title %}Contact{% endblock title %}
{% block content %}
<div class="group">
  {% if name %}
  <div class="alert alert-success text-center" role="alert">
     <h4>Thanks {{name}} for reaching out to us</h4>
     <p>We will get in touch with you as soon as possible</p>
  </div>
  {% else %}
    <div class="card">
        <div class="heading text-center">
            <h3>Send me a message</h3>
            <p class="text-center text-muted">Feel free to get in touch with me with anything related to this website or you can just say hi 👋 I will get back to you as soon as I can.
            </p>
        </div> <br>
        <form autocomplete="off" class="row" action="{% url 'contact' %}" method="POST">
            {% csrf_token %}
            <div class="col-md-12 input-wrapper">
              <input type="text" class="form-control input" placeholder="Name" name="name" id="">
            </div>
            <div class="col-md-12 input-wrapper">
              <input type="email" class="form-control input" placeholder="Email" name="email" id="">
            </div>
            <div class="col-md-12 input-wrapper">
                <input type="text" class="form-control input" placeholder="Subject" name="subject" id="">
              </div>
            <div class="col-12 input-wrapper">
              <textarea rows="5" class="form-control input" placeholder="Message" name="message" id=""></textarea>
            </div>
            <div class="col-12 text-center input-wrapper">
              <button type="submit" class="btn shadow-none">Send</button>
            </div>
        </form>
    </div>
  {% endif %}
</div>
{% endblock content %}

projects/templates/projects/index.html
{% extends 'base.html' %}
{% block title %}Projects{% endblock title %}
{% block content %}
{% load static %}
<div class="group">
    <!--
    <div class="card banner shadow">
        <small class="text-muted">Free UI designs and Bootstrap templates</small>
        <h3 class="mt-1">Weekly FREE UI Resources</h3>
        {% if category_menu %}
        <div class="categories mt-1">
            <a href="{% url 'projects:project-home' %}" data-bs-toggle="tooltip" data-bs-placement="top" title="All"><div class="software-item shadow all mt-2">All</div></a>
            {% for item in category_menu %}
            <a href="{% url 'projects:category-page' item %}" data-bs-toggle="tooltip" data-bs-placement="top" title="{{item}}"><div class="software-item shadow {{item}} mt-2"></div></a>
            {% endfor %}
        </div>
        {% endif %}
    </div>
-->
    <div class="mt-5">
        <div class="row">
            {% for project in projects %}
            <div class="col-md-4 p-2 con">
                <a href="{% url 'projects:project-detail' project.pk %}" data-bs-toggle="tooltip" data-bs-placement="top" title="Click to know more">
                    <div class="card project-card" id="card">
                        <img src="{{project.image}}" class="card-img-top" alt="...">
                       
                        <div class="card-img-overlay">
                        <div class="software-item
                            {% if project.category == 'Figma' %}figma{% endif %}
                            {% if project.category == 'Sketch' %}sketch{% endif %}
                            {% if project.category == 'XD' %}xd{% endif %}
                            {% if project.category == 'Bootstrap' %}bootstrap{% endif %}">
                        </div>
                        <!--
                            <h5 class="card-title">{{project.title}}</h5>-->
                        </div>
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
    
{% endblock content %}

projects/templates/projects/project-detail.html
{% extends 'base.html' %}
{% block title %}{{project.title}}{% endblock title %}
{% block content %}

<div class="group">
    <div class="row">
        <div class="col-12 col-md-8">
            <img class="img-fluid" src="{{project.image}}" alt="">
        </div>
        <div class="col-12 col-md-4 mt-3">
            <div>
                <h2 class="mb-4">{{project.title}}</h2>
                {% if project.case_study_file %}
                    <a class="link" href="{{project.case_study_file}}" target="_blank">View or download case study</a>
                {% endif %}
                <div class="description mt-3">
                    <div class="card text-white bg-primary">
                        <div class="card-header"><b>Challenge</b></div>
                        <div class="card-body">
                          <p class="card-text">{{project.description}}</p>
                        </div>
                      </div>
                </div>
            {% if project.file %}
            <a class="btn download-btn btn-outline-dark shadow-none" href="{{project.file}}" download="{{project.file.url}}">Download Project</a>
            {% endif %}
            </div>
            {% if project.color_palette %}
            <div class="color-palette-pannel card mt-3 p-3 text-center">
                <div class="heading">
                    <h3>Color Palette</h3>
                    <p class="text-muted">Colors used for this project</p>
                </div>
                <div class="row color-container">
                    {% if project.color %}
                        <div class="card mb-3 col-md-5 color-wrapper">
                            <div class="row">
                                <div class="col-md-3 col-3 color-preview" id="color"></div>
                                    <div class="col-md-9 col-9">
                                        <div class="card-body">
                                        <p class="card-text text-muted">{{project.color}}</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endif %}

                    {% if project.color1 %}
                        <div class="card mb-3 col-md-5 color-wrapper">
                            <div class="row">
                                <div class="col-md-3 col-3 color-preview" id="color1">
                                </div>
                                <div class="col-md-9 col-9">
                                    <div class="card-body">
                                    <p class="card-text text-muted">{{project.color}}</p>
                                </div>
                            </div>
                            </div>
                        </div>
                    {% endif %}

                    {% if project.color2 %}
                        <div class="card mb-3 col-md-5 color-wrapper">
                            <div class="row">
                                <div class="col-md-3 col-3 color-preview" id="color2">
                                </div>
                                <div class="col-md-9 col-9">
                                    <div class="card-body">
                                    <p class="card-text text-muted">{{project.color}}</p>
                                </div>
                            </div>
                            </div>
                        </div>
                    {% endif %}

                    {% if project.color3 %}
                        <div class="card mb-3 col-md-5 color-wrapper">
                            <div class="row">
                                <div class="col-md-3 col-3 color-preview" id="color3">
                                </div>
                                <div class="col-md-9 col-9">
                                    <div class="card-body">
                                    <p class="card-text text-muted">{{project.color}}</p>
                                </div>
                            </div>
                            </div>
                        </div>
                    {% endif %}

                </div>
            </div>
            {% endif %}

        </div>
    </div>
</div>

<script>
    document.getElementById('color').style.backgroundColor = '{{project.color}}';
    document.getElementById('color1').style.backgroundColor = '{{project.color1}}';
    document.getElementById('color2').style.backgroundColor = '{{project.color2}}';
    document.getElementById('color3').style.backgroundColor = '{{project.color3}}';
</script>

{% endblock content %}

templates/base.html
<!doctype html>
<html lang="en">
  <head>
  {% url 'projects:project-home' as project_home %}
  {% url 'about' as about %}
  {% url 'contact' as contact %}
  {% url 'projects:project-detail' project.pk as project_detail %}
  {% url 'projects:category-page' category_name as project_category %}

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load static %}
    <!-- Bootstrap CSS -->
    <link href="{% static 'bootstrap-5/css/bootstrap.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'scss/navbar/navbar.css' %}">
    <link rel="stylesheet" href="{% static 'scss/footer/footer.css' %}">
    <link rel="stylesheet" href="{% static 'scss/preloader/preloader.css' %}">
    {% if request.path == project_home %}
      <link rel="stylesheet" href="{% static 'scss/project-page/project.css' %}">
    {% endif %}
    {% if request.path == project_detail %}
      <link rel="stylesheet" href="{% static 'scss/project-detail/project-detail.css' %}">
    {% endif %}
    {% if request.path == about %}
      <link rel="stylesheet" href="{% static 'scss/about-page/about.css' %}">
    {% endif %}
    {% if request.path == contact %}
      <link rel="stylesheet" href="{% static 'scss/contact-page/contact.css' %}">
    {% endif %}
    {% if request.path == project_category %}
      <link rel="stylesheet" href="{% static 'scss/category-page/category.css' %}">
    {% endif %}

    <link rel="icon" href="{% static 'images/icon.svg' %}">
    <title>{% block title %}{% endblock title %}</title>
  </head>

  <div class="loader_bg fixed-top shadow">
    <div class="loader text-center">
      <img src="{% static 'images/logo.svg' %}" alt=""> <br>
      <div class="mt-2">
        <span class="sr-only">Loading...</span>
      </div>
    </div>
  </div>

  <body>
    {% include 'navbar.html' %}
    <div class="container content">
    {% block content %}{% endblock content %}
    </div>
    {% include 'footer.html' %}
    {% include 'scripts.html' %}
  </body>
</html>

templates/footer.html
<footer class="footer fixed-bottom">
    <div class="container footer-text">
        © Joise MP 2021
    </div>
</footer>

templates/navbar.html
{% load static %}
{% url 'projects:project-home' as project_home %}
{% url 'about' as about %}
{% url 'contact' as contact %}

<nav id="navbar" class="navbar navbar-expand-lg navbar-light fixed-top shadow">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'projects:project-home' %}"><img class="nav-logo" src="{% static 'images/logo.svg' %}" alt=""></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <div class="hamburger" onclick="myFunction(this)">
            <div class="bar1"></div>
            <div class="bar2"></div>
            <div class="bar3"></div>
          </div>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mb-2 mb-lg-0 ms-auto">
          <li class="nav-item">
            <a class="nav-link {% if request.path == project_home %}active{% endif %}" aria-current="page" href="{% url 'projects:project-home' %}">Projects</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if request.path == about %}active{% endif %}" href="{% url 'about' %}">About</a>
          </li>
          <li class="nav-item {% if request.path == contact %}active{% endif %}">
            <a class="nav-link" href="{% url 'contact' %}">Contact</a>
          </li>
        </ul>
      </div>
    </div>
</nav>

templates/scripts.html
{% load static %}
<script src="{% static 'js/navbar-scroll-hide.js' %}"></script>
<script src="{% static 'js/menu-icon.js' %}"></script>
<script src="{% static 'js/preloader.js' %}"></script>
<script src="{% static 'bootstrap-5/js/bootstrap.bundle.min.js' %}" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous">//bootstrap.bundle.min.js</script>